-- GroovyShelves live Supabase schema baseline
-- Captured from project dsespqmqqeoucnglaehf on 2026-09-18.
-- This is a rebuild baseline, NOT a migration to run against the existing live project.
-- User data and the 603k-row MusicBrainz catalog are intentionally not included.
-- Apply on a fresh Supabase project only.

begin;

create extension if not exists pgcrypto;

-- Adopt Supabase's upcoming explicit Data API exposure model for future objects.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;

-- Tables
create table public.album_ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid,
  album_id bigint NOT NULL,
  rating integer,
  created_at timestamp with time zone DEFAULT now()
);
create table public.albums (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  artist_id bigint,
  title text NOT NULL,
  release_year integer,
  genre text,
  cover_url text,
  created_at timestamp with time zone DEFAULT now(),
  discogs_master_id text,
  apple_collection_url text
);
create table public.apple_artwork_cache (
  discogs_master_id bigint NOT NULL,
  artist_name text NOT NULL,
  album_title text NOT NULL,
  release_year smallint,
  apple_collection_id bigint,
  apple_collection_url text NOT NULL,
  artwork_url text NOT NULL,
  matched_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
create table public.artists (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);
create table public.collections (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid,
  album_id bigint NOT NULL,
  collection_number text,
  added_at timestamp with time zone DEFAULT now(),
  sort_order integer NOT NULL,
  cover_url text,
  discogs_release_id bigint,
  media_condition text,
  sleeve_condition text,
  pressing_country text,
  pressing_year integer,
  pressing_label text,
  catalog_number text,
  matrix_runout_a text,
  matrix_runout_b text,
  pressing_match_status text,
  matrix_runout_c text,
  matrix_runout_d text,
  discogs_style text,
  matrix_runout_e text,
  matrix_runout_f text,
  matrix_runout_g text,
  matrix_runout_h text,
  shelf_id uuid,
  shelf_sort_order integer
);
create table public.musicbrainz_catalog (
  mbid uuid NOT NULL,
  discogs_master_id bigint NOT NULL,
  artist_name text NOT NULL,
  album_title text NOT NULL,
  first_release_year smallint,
  secondary_types text,
  match_type text NOT NULL
);
create table public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  notification_type text NOT NULL,
  item_count integer DEFAULT 1 NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  read_at timestamp with time zone
);
create table public.profiles (
  id uuid NOT NULL,
  username text NOT NULL,
  display_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  bio text DEFAULT ''::text NOT NULL,
  favorite_artist text DEFAULT ''::text NOT NULL,
  favorite_genre text DEFAULT ''::text NOT NULL,
  collecting_since smallint,
  grail_record text DEFAULT ''::text NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  grail_discogs_master_id text,
  grail_title text DEFAULT ''::text NOT NULL,
  grail_artist text DEFAULT ''::text NOT NULL,
  grail_year smallint,
  grail_cover_url text DEFAULT ''::text NOT NULL,
  grail_apple_url text DEFAULT ''::text NOT NULL
);
create table public.shelves (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  icon text DEFAULT 'record'::text NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  color text DEFAULT '#E85301'::text NOT NULL
);
create table public.tracks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  album_id bigint NOT NULL,
  disc_side text,
  track_number integer,
  title text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);
create table public.user_follows (
  follower_id uuid NOT NULL,
  followed_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
create table public.wishlists (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  album_id bigint NOT NULL,
  added_at timestamp with time zone DEFAULT now() NOT NULL,
  sort_order integer,
  cover_url text,
  discogs_style text
);

-- Constraints
alter table public.album_ratings add constraint album_ratings_album_id_fkey FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE;
alter table public.album_ratings add constraint album_ratings_pkey PRIMARY KEY (id);
alter table public.album_ratings add constraint album_ratings_rating_check CHECK (rating >= 0 AND rating <= 5);
alter table public.album_ratings add constraint album_ratings_user_id_album_id_key UNIQUE (user_id, album_id);
alter table public.album_ratings add constraint album_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.albums add constraint albums_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE SET NULL;
alter table public.albums add constraint albums_pkey PRIMARY KEY (id);
alter table public.apple_artwork_cache add constraint apple_artwork_cache_pkey PRIMARY KEY (discogs_master_id);
alter table public.artists add constraint artists_pkey PRIMARY KEY (id);
alter table public.collections add constraint collections_album_id_fkey FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE;
alter table public.collections add constraint collections_media_condition_check CHECK (media_condition IS NULL OR (media_condition = ANY (ARRAY['M'::text, 'NM'::text, 'VG+'::text, 'VG'::text, 'G+'::text, 'G'::text, 'F'::text, 'P'::text])));
alter table public.collections add constraint collections_pkey PRIMARY KEY (id);
alter table public.collections add constraint collections_pressing_match_status_check CHECK (pressing_match_status IS NULL OR pressing_match_status = 'discogs'::text);
alter table public.collections add constraint collections_shelf_id_fkey FOREIGN KEY (shelf_id) REFERENCES shelves(id) ON DELETE SET NULL;
alter table public.collections add constraint collections_sleeve_condition_check CHECK (sleeve_condition IS NULL OR (sleeve_condition = ANY (ARRAY['M'::text, 'NM'::text, 'VG+'::text, 'VG'::text, 'G+'::text, 'G'::text, 'F'::text, 'P'::text, 'NO_COVER'::text])));
alter table public.collections add constraint collections_user_id_album_id_key UNIQUE (user_id, album_id);
alter table public.collections add constraint collections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.musicbrainz_catalog add constraint musicbrainz_catalog_pkey PRIMARY KEY (mbid);
alter table public.notifications add constraint notifications_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_item_count_check CHECK (item_count > 0);
alter table public.notifications add constraint notifications_pkey PRIMARY KEY (id);
alter table public.notifications add constraint notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_type_check CHECK (notification_type = ANY (ARRAY['new_follower'::text, 'collection_activity'::text, 'wishlist_match'::text]));
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_username_key UNIQUE (username);
alter table public.shelves add constraint shelves_name_check CHECK (char_length(TRIM(BOTH FROM name)) >= 1 AND char_length(TRIM(BOTH FROM name)) <= 30);
alter table public.shelves add constraint shelves_pkey PRIMARY KEY (id);
alter table public.shelves add constraint shelves_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.tracks add constraint tracks_album_id_fkey FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE;
alter table public.tracks add constraint tracks_pkey PRIMARY KEY (id);
alter table public.user_follows add constraint user_follows_followed_id_fkey FOREIGN KEY (followed_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.user_follows add constraint user_follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.user_follows add constraint user_follows_not_self CHECK (follower_id <> followed_id);
alter table public.user_follows add constraint user_follows_pkey PRIMARY KEY (follower_id, followed_id);
alter table public.wishlists add constraint wishlists_album_id_fkey FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE;
alter table public.wishlists add constraint wishlists_pkey PRIMARY KEY (id);
alter table public.wishlists add constraint wishlists_user_album_unique UNIQUE (user_id, album_id);
alter table public.wishlists add constraint wishlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Non-constraint indexes
CREATE INDEX album_ratings_album_id_idx ON public.album_ratings USING btree (album_id);
CREATE INDEX albums_artist_id_idx ON public.albums USING btree (artist_id);
CREATE UNIQUE INDEX albums_discogs_master_id_uidx ON public.albums USING btree (discogs_master_id) WHERE (discogs_master_id IS NOT NULL);
CREATE INDEX apple_artwork_cache_matched_at_idx ON public.apple_artwork_cache USING btree (matched_at DESC);
CREATE INDEX collections_album_id_idx ON public.collections USING btree (album_id);
CREATE INDEX collections_discogs_release_id_idx ON public.collections USING btree (discogs_release_id) WHERE (discogs_release_id IS NOT NULL);
CREATE INDEX collections_shelf_id_idx ON public.collections USING btree (shelf_id) WHERE (shelf_id IS NOT NULL);
CREATE INDEX collections_user_shelf_idx ON public.collections USING btree (user_id, shelf_id);
CREATE INDEX collections_user_sort_order_idx ON public.collections USING btree (user_id, sort_order);
CREATE INDEX musicbrainz_catalog_discogs_master_id_idx ON public.musicbrainz_catalog USING btree (discogs_master_id) WHERE (discogs_master_id IS NOT NULL);
CREATE INDEX notifications_actor_id_idx ON public.notifications USING btree (actor_id);
CREATE INDEX notifications_recipient_unread_idx ON public.notifications USING btree (recipient_id, updated_at DESC) WHERE (read_at IS NULL);
CREATE INDEX notifications_recipient_updated_idx ON public.notifications USING btree (recipient_id, updated_at DESC);
CREATE UNIQUE INDEX profiles_username_lower_unique ON public.profiles USING btree (lower(username)) WHERE (username IS NOT NULL);
CREATE INDEX shelves_user_sort_idx ON public.shelves USING btree (user_id, sort_order, created_at);
CREATE INDEX tracks_album_id_idx ON public.tracks USING btree (album_id);
CREATE INDEX user_follows_created_at_idx ON public.user_follows USING btree (created_at DESC);
CREATE INDEX user_follows_followed_id_idx ON public.user_follows USING btree (followed_id);
CREATE INDEX wishlists_album_id_idx ON public.wishlists USING btree (album_id);
CREATE INDEX wishlists_user_id_idx ON public.wishlists USING btree (user_id);
CREATE INDEX wishlists_user_sort_order_idx ON public.wishlists USING btree (user_id, sort_order);

-- Functions / RPCs / trigger functions
CREATE OR REPLACE FUNCTION public.delete_collection_record(p_collection_id text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_old_shelf_id uuid;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select c.shelf_id
  into v_old_shelf_id
  from public.collections c
  where c.id::text = p_collection_id
    and c.user_id = v_user_id
  for update;

  if not found then
    raise exception 'Collection record not found';
  end if;

  delete from public.collections
  where id::text = p_collection_id
    and user_id = v_user_id;

  with ranked as (
    select
      c.id,
      row_number() over (order by c.sort_order nulls last, c.id) as new_order
    from public.collections c
    where c.user_id = v_user_id
  )
  update public.collections c
  set sort_order = ranked.new_order::integer
  from ranked
  where c.id = ranked.id;

  if v_old_shelf_id is not null then
    with ranked as (
      select
        c.id,
        row_number() over (
          order by c.shelf_sort_order nulls last, c.sort_order nulls last, c.id
        ) as new_order
      from public.collections c
      where c.user_id = v_user_id
        and c.shelf_id = v_old_shelf_id
    )
    update public.collections c
    set shelf_sort_order = ranked.new_order::integer
    from ranked
    where c.id = ranked.id;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.delete_shelf_and_unshelve(p_shelf_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_count integer := 0;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if not exists (
    select 1
    from public.shelves s
    where s.id = p_shelf_id
      and s.user_id = v_user_id
  ) then
    raise exception 'Shelf not found';
  end if;

  update public.collections
  set shelf_id = null,
      shelf_sort_order = null
  where user_id = v_user_id
    and shelf_id = p_shelf_id;

  get diagnostics v_count = row_count;

  delete from public.shelves
  where id = p_shelf_id
    and user_id = v_user_id;

  return v_count;
end;
$function$;

CREATE OR REPLACE FUNCTION public.enforce_shelf_limit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform pg_advisory_xact_lock(hashtext(new.user_id::text));

  if (
    select count(*)
    from public.shelves
    where user_id = new.user_id
  ) >= 10 then
    raise exception 'Maximum 10 shelves per user';
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_following_overview()
 RETURNS TABLE(user_id uuid, username text, avatar_url text, followed_at timestamp with time zone, collection_count bigint, wishlist_count bigint, common_count bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public', 'pg_temp'
AS $function$
  select
    f.followed_id as user_id,
    p.username,
    p.avatar_url,
    f.created_at as followed_at,
    (select count(*) from public.collections c where c.user_id = f.followed_id)::bigint as collection_count,
    (select count(*) from public.wishlists w where w.user_id = f.followed_id)::bigint as wishlist_count,
    (
      select count(distinct mine.album_id)
      from public.collections mine
      left join public.albums mine_album on mine_album.id = mine.album_id
      where mine.user_id = auth.uid()
        and exists (
          select 1
          from public.collections theirs
          left join public.albums their_album on their_album.id = theirs.album_id
          where theirs.user_id = f.followed_id
            and (
              theirs.album_id = mine.album_id
              or (
                mine_album.discogs_master_id is not null
                and their_album.discogs_master_id = mine_album.discogs_master_id
              )
            )
        )
    )::bigint as common_count
  from public.user_follows f
  join public.profiles p on p.id = f.followed_id
  where f.follower_id = auth.uid()
  order by f.created_at desc;
$function$;

CREATE OR REPLACE FUNCTION public.get_following_statistics()
 RETURNS TABLE(user_id uuid, username text, avatar_url text, common_count bigint, taste_similarity numeric)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public', 'pg_temp'
AS $function$
  with followed as (
    select f.followed_id
    from public.user_follows f
    where f.follower_id = auth.uid()
  ),
  relevant_users as (
    select auth.uid() as user_id
    union
    select followed_id from followed
  ),
  genre_tokens as (
    select
      c.user_id,
      lower(btrim(token.genre_token)) as genre_token,
      count(*)::numeric as genre_count
    from public.collections c
    left join public.albums a on a.id = c.album_id
    join relevant_users ru on ru.user_id = c.user_id
    cross join lateral regexp_split_to_table(
      coalesce(nullif(btrim(c.discogs_style),''),nullif(btrim(a.genre),''),''),
      E'\\s*[·,]\\s*'
    ) as token(genre_token)
    where btrim(token.genre_token) <> ''
    group by c.user_id, lower(btrim(token.genre_token))
  ),
  genre_totals as (
    select user_id,sum(genre_count)::numeric as genre_total
    from genre_tokens
    group by user_id
  ),
  taste as (
    select
      f.followed_id,
      case
        when coalesce(own_total.genre_total,0) = 0 or coalesce(their_total.genre_total,0) = 0 then 0::numeric
        else round(
          coalesce(sum(least(
            own_genre.genre_count / own_total.genre_total,
            coalesce(their_genre.genre_count / their_total.genre_total,0)
          )),0) * 100,
          1
        )
      end as taste_similarity
    from followed f
    left join genre_totals own_total on own_total.user_id = auth.uid()
    left join genre_totals their_total on their_total.user_id = f.followed_id
    left join genre_tokens own_genre on own_genre.user_id = auth.uid()
    left join genre_tokens their_genre
      on their_genre.user_id = f.followed_id
     and their_genre.genre_token = own_genre.genre_token
    group by f.followed_id,own_total.genre_total,their_total.genre_total
  )
  select
    f.followed_id as user_id,
    p.username,
    p.avatar_url,
    (
      select count(distinct mine.album_id)
      from public.collections mine
      left join public.albums mine_album on mine_album.id = mine.album_id
      where mine.user_id = auth.uid()
        and exists (
          select 1
          from public.collections theirs
          left join public.albums their_album on their_album.id = theirs.album_id
          where theirs.user_id = f.followed_id
            and (
              theirs.album_id = mine.album_id
              or (
                mine_album.discogs_master_id is not null
                and their_album.discogs_master_id = mine_album.discogs_master_id
              )
            )
        )
    )::bigint as common_count,
    coalesce(t.taste_similarity,0)::numeric as taste_similarity
  from followed f
  join public.profiles p on p.id = f.followed_id
  left join taste t on t.followed_id = f.followed_id
  order by p.username;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'username',
      split_part(new.email, '@', 1)
    )
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.move_collection_to_shelf(p_collection_id text, p_shelf_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_old_shelf_id uuid;
  v_new_order integer;
  v_result jsonb;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select c.shelf_id
  into v_old_shelf_id
  from public.collections c
  where c.id::text = p_collection_id
    and c.user_id = v_user_id
  for update;

  if not found then
    raise exception 'Collection record not found';
  end if;

  if p_shelf_id is not null then
    perform 1
    from public.shelves s
    where s.id = p_shelf_id
      and s.user_id = v_user_id
    for update;

    if not found then
      raise exception 'Shelf not found';
    end if;
  end if;

  if v_old_shelf_id is not distinct from p_shelf_id then
    select jsonb_build_object(
      'shelf_id', c.shelf_id,
      'shelf_sort_order', c.shelf_sort_order
    )
    into v_result
    from public.collections c
    where c.id::text = p_collection_id
      and c.user_id = v_user_id;

    return v_result;
  end if;

  if p_shelf_id is null then
    update public.collections
    set shelf_id = null,
        shelf_sort_order = null
    where id::text = p_collection_id
      and user_id = v_user_id;
  else
    select coalesce(max(c.shelf_sort_order), 0) + 1
    into v_new_order
    from public.collections c
    where c.user_id = v_user_id
      and c.shelf_id = p_shelf_id;

    update public.collections
    set shelf_id = p_shelf_id,
        shelf_sort_order = v_new_order
    where id::text = p_collection_id
      and user_id = v_user_id;
  end if;

  if v_old_shelf_id is not null then
    with ranked as (
      select
        c.id,
        row_number() over (
          order by c.shelf_sort_order nulls last, c.sort_order nulls last, c.id
        ) as new_order
      from public.collections c
      where c.user_id = v_user_id
        and c.shelf_id = v_old_shelf_id
    )
    update public.collections c
    set shelf_sort_order = ranked.new_order::integer
    from ranked
    where c.id = ranked.id;
  end if;

  select jsonb_build_object(
    'shelf_id', c.shelf_id,
    'shelf_sort_order', c.shelf_sort_order
  )
  into v_result
  from public.collections c
  where c.id::text = p_collection_id
    and c.user_id = v_user_id;

  return v_result;
end;
$function$;

CREATE OR REPLACE FUNCTION public.notify_followers_collection_activity()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  follower record;
  existing_notification_id bigint;
  album_title text := '';
  album_artist text := '';
  album_cover text := '';
  recipient_has_album boolean := false;
  previous_shared_count integer := 0;
begin
  select
    coalesce(a.title,''),
    coalesce(ar.name,''),
    coalesce(new.cover_url,a.cover_url,'')
  into album_title, album_artist, album_cover
  from public.albums a
  left join public.artists ar on ar.id = a.artist_id
  where a.id = new.album_id;

  for follower in
    select uf.follower_id
    from public.user_follows uf
    where uf.followed_id = new.user_id
  loop
    select exists (
      select 1
      from public.collections mine
      left join public.albums mine_album on mine_album.id = mine.album_id
      left join public.albums added_album on added_album.id = new.album_id
      where mine.user_id = follower.follower_id
        and (
          mine.album_id = new.album_id
          or (
            added_album.discogs_master_id is not null
            and mine_album.discogs_master_id = added_album.discogs_master_id
          )
        )
    ) into recipient_has_album;

    existing_notification_id := null;

    update public.notifications n
    set
      item_count = n.item_count + 1,
      payload = coalesce(n.payload,'{}'::jsonb) || jsonb_build_object(
        'album_id', new.album_id,
        'album_title', album_title,
        'album_artist', album_artist,
        'cover_url', album_cover,
        'shared_count', coalesce(nullif(n.payload->>'shared_count','')::integer,0) + case when recipient_has_album then 1 else 0 end,
        'last_shared_album_title', case when recipient_has_album then album_title else coalesce(n.payload->>'last_shared_album_title','') end,
        'last_shared_album_artist', case when recipient_has_album then album_artist else coalesce(n.payload->>'last_shared_album_artist','') end
      ),
      updated_at = now()
    where n.recipient_id = follower.follower_id
      and n.actor_id = new.user_id
      and n.notification_type = 'collection_activity'
      and n.read_at is null
      and n.created_at >= now() - interval '2 hours'
    returning n.id into existing_notification_id;

    if existing_notification_id is null then
      insert into public.notifications (
        recipient_id,
        actor_id,
        notification_type,
        item_count,
        payload,
        created_at,
        updated_at
      ) values (
        follower.follower_id,
        new.user_id,
        'collection_activity',
        1,
        jsonb_build_object(
          'album_id', new.album_id,
          'album_title', album_title,
          'album_artist', album_artist,
          'cover_url', album_cover,
          'shared_count', case when recipient_has_album then 1 else 0 end,
          'last_shared_album_title', case when recipient_has_album then album_title else '' end,
          'last_shared_album_artist', case when recipient_has_album then album_artist else '' end
        ),
        now(),
        now()
      );
    end if;
  end loop;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.notify_followers_wishlist_match()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  follower record;
  existing_notification_id bigint;
  album_title text := '';
  album_artist text := '';
  album_cover text := '';
  recipient_has_album boolean := false;
begin
  select
    coalesce(a.title,''),
    coalesce(ar.name,''),
    coalesce(new.cover_url,a.cover_url,'')
  into album_title, album_artist, album_cover
  from public.albums a
  left join public.artists ar on ar.id = a.artist_id
  where a.id = new.album_id;

  for follower in
    select uf.follower_id
    from public.user_follows uf
    where uf.followed_id = new.user_id
  loop
    select exists (
      select 1
      from public.collections mine
      left join public.albums mine_album on mine_album.id = mine.album_id
      left join public.albums wish_album on wish_album.id = new.album_id
      where mine.user_id = follower.follower_id
        and (
          mine.album_id = new.album_id
          or (
            wish_album.discogs_master_id is not null
            and mine_album.discogs_master_id = wish_album.discogs_master_id
          )
        )
    ) into recipient_has_album;

    if recipient_has_album then
      existing_notification_id := null;

      update public.notifications n
      set
        item_count = n.item_count + 1,
        payload = coalesce(n.payload,'{}'::jsonb) || jsonb_build_object(
          'album_id', new.album_id,
          'album_title', album_title,
          'album_artist', album_artist,
          'cover_url', album_cover
        ),
        updated_at = now()
      where n.recipient_id = follower.follower_id
        and n.actor_id = new.user_id
        and n.notification_type = 'wishlist_match'
        and n.read_at is null
        and n.created_at >= now() - interval '2 hours'
      returning n.id into existing_notification_id;

      if existing_notification_id is null then
        insert into public.notifications (
          recipient_id,
          actor_id,
          notification_type,
          item_count,
          payload,
          created_at,
          updated_at
        ) values (
          follower.follower_id,
          new.user_id,
          'wishlist_match',
          1,
          jsonb_build_object(
            'album_id', new.album_id,
            'album_title', album_title,
            'album_artist', album_artist,
            'cover_url', album_cover
          ),
          now(),
          now()
        );
      end if;
    end if;
  end loop;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.notify_new_follower()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
  insert into public.notifications (
    recipient_id,
    actor_id,
    notification_type,
    item_count,
    payload,
    created_at,
    updated_at
  ) values (
    new.followed_id,
    new.follower_id,
    'new_follower',
    1,
    '{}'::jsonb,
    now(),
    now()
  );
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.profile_public_counts(target_profile_id uuid)
 RETURNS TABLE(collection_count bigint, wishlist_count bigint, shelf_count bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select
    (select count(*) from public.collections where user_id = target_profile_id),
    (select count(*) from public.wishlists where user_id = target_profile_id),
    (select count(*) from public.shelves where user_id = target_profile_id);
$function$;

CREATE OR REPLACE FUNCTION public.set_collection_display_order(p_shelf_id uuid, p_collection_ids jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if jsonb_typeof(p_collection_ids) <> 'array' then
    raise exception 'p_collection_ids must be a JSON array';
  end if;

  if p_shelf_id is null then
    with ordered as (
      select id_text, ordinality::integer as new_order
      from jsonb_array_elements_text(p_collection_ids) with ordinality as item(id_text, ordinality)
    )
    update public.collections c
    set sort_order = ordered.new_order
    from ordered
    where c.id::text = ordered.id_text
      and c.user_id = v_user_id;
  else
    if not exists (
      select 1
      from public.shelves s
      where s.id = p_shelf_id
        and s.user_id = v_user_id
    ) then
      raise exception 'Shelf not found';
    end if;

    with ordered as (
      select id_text, ordinality::integer as new_order
      from jsonb_array_elements_text(p_collection_ids) with ordinality as item(id_text, ordinality)
    )
    update public.collections c
    set shelf_sort_order = ordered.new_order
    from ordered
    where c.id::text = ordered.id_text
      and c.user_id = v_user_id
      and c.shelf_id = p_shelf_id;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_wishlist_display_order(p_wishlist_ids jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if jsonb_typeof(p_wishlist_ids) <> 'array' then
    raise exception 'p_wishlist_ids must be a JSON array';
  end if;

  with ordered as (
    select id_text, ordinality::integer as new_order
    from jsonb_array_elements_text(p_wishlist_ids) with ordinality as item(id_text, ordinality)
  )
  update public.wishlists w
  set sort_order = ordered.new_order
  from ordered
  where w.id::text = ordered.id_text
    and w.user_id = v_user_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.upsert_apple_artwork_cache(p_matches jsonb)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  item jsonb;
  saved_count integer := 0;
  v_master_id bigint;
  v_artist text;
  v_title text;
  v_year integer;
  v_collection_id bigint;
  v_collection_url text;
  v_artwork_url text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if p_matches is null or jsonb_typeof(p_matches) <> 'array' then
    raise exception 'p_matches must be a JSON array';
  end if;

  if jsonb_array_length(p_matches) > 200 then
    raise exception 'Too many cache rows';
  end if;

  for item in
    select value from jsonb_array_elements(p_matches)
  loop
    begin
      v_master_id := nullif(item->>'discogs_master_id','')::bigint;
    exception when others then
      continue;
    end;

    v_artist := left(trim(coalesce(item->>'artist_name','')),300);
    v_title := left(trim(coalesce(item->>'album_title','')),500);

    begin
      v_year := nullif(item->>'release_year','')::integer;
    exception when others then
      v_year := null;
    end;

    if v_year is not null and (v_year < 1800 or v_year > 2100) then
      v_year := null;
    end if;

    begin
      v_collection_id := nullif(item->>'apple_collection_id','')::bigint;
    exception when others then
      v_collection_id := null;
    end;

    v_collection_url := left(trim(coalesce(item->>'apple_collection_url','')),1500);
    v_artwork_url := left(trim(coalesce(item->>'artwork_url','')),1500);

    if v_master_id is null or v_master_id <= 0 or v_artist = '' or v_title = '' then
      continue;
    end if;

    -- Only accept Apple's own album links and artwork CDN URLs.
    if v_collection_url !~* '^https://(music|itunes)\.apple\.com/' then
      continue;
    end if;

    if v_artwork_url !~* '^https://[^/]*mzstatic\.com/' then
      continue;
    end if;

    insert into public.apple_artwork_cache (
      discogs_master_id,
      artist_name,
      album_title,
      release_year,
      apple_collection_id,
      apple_collection_url,
      artwork_url,
      matched_at,
      updated_at
    ) values (
      v_master_id,
      v_artist,
      v_title,
      v_year,
      v_collection_id,
      v_collection_url,
      v_artwork_url,
      now(),
      now()
    )
    on conflict (discogs_master_id) do update set
      artist_name = excluded.artist_name,
      album_title = excluded.album_title,
      release_year = excluded.release_year,
      apple_collection_id = excluded.apple_collection_id,
      apple_collection_url = excluded.apple_collection_url,
      artwork_url = excluded.artwork_url,
      matched_at = now(),
      updated_at = now();

    saved_count := saved_count + 1;
  end loop;

  return saved_count;
end;
$function$;

CREATE OR REPLACE FUNCTION public.validate_collection_shelf_owner()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.shelf_id is null then
    new.shelf_sort_order := null;
    return new;
  end if;

  if not exists (
    select 1
    from public.shelves s
    where s.id = new.shelf_id
      and s.user_id = new.user_id
  ) then
    raise exception 'Shelf must belong to the same user as the collection record';
  end if;

  return new;
end;
$function$;


-- Triggers
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER collections_notify_followers_after_insert AFTER INSERT ON collections FOR EACH ROW EXECUTE FUNCTION notify_followers_collection_activity();
CREATE TRIGGER validate_collection_shelf_owner_trigger BEFORE INSERT OR UPDATE OF shelf_id, user_id, shelf_sort_order ON collections FOR EACH ROW EXECUTE FUNCTION validate_collection_shelf_owner();
CREATE TRIGGER enforce_shelf_limit_trigger BEFORE INSERT ON shelves FOR EACH ROW EXECUTE FUNCTION enforce_shelf_limit();
CREATE TRIGGER user_follows_notify_after_insert AFTER INSERT ON user_follows FOR EACH ROW EXECUTE FUNCTION notify_new_follower();
CREATE TRIGGER wishlists_notify_followers_after_insert AFTER INSERT ON wishlists FOR EACH ROW EXECUTE FUNCTION notify_followers_wishlist_match();

-- Row Level Security
alter table public.album_ratings enable row level security;
alter table public.albums enable row level security;
alter table public.apple_artwork_cache enable row level security;
alter table public.artists enable row level security;
alter table public.collections enable row level security;
alter table public.musicbrainz_catalog enable row level security;
alter table public.notifications enable row level security;
alter table public.profiles enable row level security;
alter table public.shelves enable row level security;
alter table public.tracks enable row level security;
alter table public.user_follows enable row level security;
alter table public.wishlists enable row level security;

-- RLS policies
create policy "Authenticated users can read album ratings" on public.album_ratings as PERMISSIVE for SELECT to authenticated
  using (true);
create policy "Users can add own album ratings" on public.album_ratings as PERMISSIVE for INSERT to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can delete own album ratings" on public.album_ratings as PERMISSIVE for DELETE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can update own album ratings" on public.album_ratings as PERMISSIVE for UPDATE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Authenticated users can insert albums" on public.albums as PERMISSIVE for INSERT to authenticated
  with check (true);
create policy "Authenticated users can read albums" on public.albums as PERMISSIVE for SELECT to authenticated
  using (true);
create policy apple_artwork_cache_public_read on public.apple_artwork_cache as PERMISSIVE for SELECT to anon, authenticated
  using (true);
create policy "Authenticated users can insert artists" on public.artists as PERMISSIVE for INSERT to authenticated
  with check (true);
create policy "Authenticated users can read artists" on public.artists as PERMISSIVE for SELECT to authenticated
  using (true);
create policy "Authenticated users can update own collections" on public.collections as PERMISSIVE for UPDATE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can add to own collection" on public.collections as PERMISSIVE for INSERT to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can remove from own collection" on public.collections as PERMISSIVE for DELETE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can view collections" on public.collections as PERMISSIVE for SELECT to authenticated
  using (true);
create policy "Catalog is publicly readable" on public.musicbrainz_catalog as PERMISSIVE for SELECT to anon, authenticated
  using (true);
create policy "Users can clear their notifications" on public.notifications as PERMISSIVE for DELETE to authenticated
  using ((( SELECT auth.uid() AS uid) = recipient_id));
create policy "Users can mark their notifications read" on public.notifications as PERMISSIVE for UPDATE to authenticated
  using ((( SELECT auth.uid() AS uid) = recipient_id))
  with check ((( SELECT auth.uid() AS uid) = recipient_id));
create policy "Users can read their notifications" on public.notifications as PERMISSIVE for SELECT to authenticated
  using ((( SELECT auth.uid() AS uid) = recipient_id));
create policy "Users can delete own profile" on public.profiles as PERMISSIVE for DELETE to authenticated
  using ((( SELECT auth.uid() AS uid) = id));
create policy "Users can insert own profile" on public.profiles as PERMISSIVE for INSERT to authenticated
  with check ((( SELECT auth.uid() AS uid) = id));
create policy "Users can update own profile" on public.profiles as PERMISSIVE for UPDATE to authenticated
  using ((( SELECT auth.uid() AS uid) = id))
  with check ((( SELECT auth.uid() AS uid) = id));
create policy profiles_public_read on public.profiles as PERMISSIVE for SELECT to anon, authenticated
  using (true);
create policy "Shelves are publicly readable" on public.shelves as PERMISSIVE for SELECT to anon, authenticated
  using (true);
create policy "Users can create own shelves" on public.shelves as PERMISSIVE for INSERT to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can delete own shelves" on public.shelves as PERMISSIVE for DELETE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can update own shelves" on public.shelves as PERMISSIVE for UPDATE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Authenticated users can insert tracks" on public.tracks as PERMISSIVE for INSERT to authenticated
  with check (true);
create policy "Authenticated users can read tracks" on public.tracks as PERMISSIVE for SELECT to authenticated
  using (true);
create policy "Users can follow from their own account" on public.user_follows as PERMISSIVE for INSERT to authenticated
  with check (((( SELECT auth.uid() AS uid) = follower_id) AND (follower_id <> followed_id)));
create policy "Users can read relevant follows" on public.user_follows as PERMISSIVE for SELECT to authenticated
  using (((( SELECT auth.uid() AS uid) = follower_id) OR (( SELECT auth.uid() AS uid) = followed_id)));
create policy "Users can unfollow from their own account" on public.user_follows as PERMISSIVE for DELETE to authenticated
  using ((( SELECT auth.uid() AS uid) = follower_id));
create policy "Authenticated users can view wishlists" on public.wishlists as PERMISSIVE for SELECT to authenticated
  using (true);
create policy "Users can add to their own wishlist" on public.wishlists as PERMISSIVE for INSERT to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can remove from their own wishlist" on public.wishlists as PERMISSIVE for DELETE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can reorder their own wishlist" on public.wishlists as PERMISSIVE for UPDATE to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id));

-- Explicit Data API grants. RLS remains the row-level authority.
grant select, insert, update, delete on public.album_ratings to authenticated;
grant select on public.albums to authenticated;
grant select on public.artists to authenticated;
grant select, insert, update, delete on public.collections to authenticated;
grant select on public.tracks to authenticated;
grant select, insert, update, delete on public.wishlists to authenticated;
grant select on public.profiles to anon, authenticated;
grant insert, update, delete on public.profiles to authenticated;
grant select on public.shelves to anon, authenticated;
grant insert, update, delete on public.shelves to authenticated;
grant select, insert, delete on public.user_follows to authenticated;
grant select, update, delete on public.notifications to authenticated;
grant select on public.musicbrainz_catalog to anon, authenticated;
grant select on public.apple_artwork_cache to anon, authenticated;

grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

-- Client-callable RPCs. Trigger helpers remain unavailable to anon/authenticated.
revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function public.delete_collection_record(text) to authenticated;
grant execute on function public.delete_shelf_and_unshelve(uuid) to authenticated;
grant execute on function public.get_following_overview() to authenticated;
grant execute on function public.get_following_statistics() to authenticated;
grant execute on function public.move_collection_to_shelf(text,uuid) to authenticated;
grant execute on function public.profile_public_counts(uuid) to authenticated;
grant execute on function public.set_collection_display_order(uuid,jsonb) to authenticated;
grant execute on function public.set_wishlist_display_order(jsonb) to authenticated;
grant execute on function public.upsert_apple_artwork_cache(jsonb) to authenticated;
grant execute on all functions in schema public to service_role;

-- Storage bucket used for profile avatars.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('profile-images','profile-images',true,null,null)
on conflict (id) do update set name=excluded.name,public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

-- Storage RLS policies
create policy "Users can delete own profile image vejz8c_0" on storage.objects as PERMISSIVE for DELETE to authenticated
  using (((bucket_id = 'profile-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "Users can update own profile image vejz8c_0" on storage.objects as PERMISSIVE for UPDATE to authenticated
  using (((bucket_id = 'profile-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "Users can upload own profile image" on storage.objects as PERMISSIVE for INSERT to authenticated
  with check (((bucket_id = 'profile-images'::text) AND (name ~~ ((auth.uid())::text || '/%'::text))));
create policy "Users can view own profile image metadata" on storage.objects as PERMISSIVE for SELECT to authenticated
  using (((bucket_id = 'profile-images'::text) AND (name ~~ ((auth.uid())::text || '/%'::text))));

commit;
