const test=require('node:test');
const assert=require('node:assert/strict');
const Controller=require('../js/grid-sort-controller.js');

function classList(){const values=new Set();return {add:name=>values.add(name),remove:name=>values.delete(name),contains:name=>values.has(name)};}
function card(index){return {index:String(index),classList:classList(),style:{},parentNode:null,nextSibling:null,getAttribute(name){return name==='data-index'?this.index:null;},getBoundingClientRect(){return {left:0,right:100,top:0,bottom:100,width:100,height:100};},cloneNode(){return card(index);},removeAttribute(){},addEventListener(){},closest(){return this;},setPointerCapture(){},releasePointerCapture(){}};}
function collection(order){const result={classList:classList(),cards:(order||[]).map(card),querySelectorAll(selector){return selector==='.record'?this.cards:[];}};result.insertBefore=function(item,reference){this.cards=this.cards.filter(value=>value!==item);const at=reference?this.cards.indexOf(reference):-1;if(at<0)this.cards.push(item);else this.cards.splice(at,0,item);this.cards.forEach((value,index)=>{value.parentNode=this;value.nextSibling=this.cards[index+1]||null;});};result.cards.forEach((value,index)=>{value.parentNode=result;value.nextSibling=result.cards[index+1]||null;});return result;}
function recordModel(){return {INDEX:{order:0,shelfSortOrder:14},order:r=>r[0],entryId:r=>r[9],shelfId:r=>r[13],shelfSortOrder:r=>r[14]};}
function harness(config){
  config=config||{};let records=config.records||[];
  const state=Object.assign({selectedRating:'all',searchQuery:'',sort:'added',viewedUserId:null,libraryView:'collection',activeShelfId:'all',page:1},config.state||{});
  const grid=config.collection||collection([]);const rpcCalls=[],alerts=[];let renders=0,reloads=0;
  const api={async rpc(name,payload){rpcCalls.push({name,payload});return config.rpcError?{error:new Error('save failed')}:{error:null};}};
  const windowListeners=new Map();
  const win={innerHeight:800,requestAnimationFrame(){return 1;},cancelAnimationFrame(){},setTimeout(fn){fn();return 1;},clearTimeout(){},scrollBy(){},addEventListener(name,fn){if(!windowListeners.has(name))windowListeners.set(name,new Set());windowListeners.get(name).add(fn);},removeEventListener(name,fn){if(windowListeners.has(name))windowListeners.get(name).delete(fn);}};
  const doc={body:{appendChild(){}},querySelectorAll(){return [];},elementFromPoint(){return null;},createElement(){return {width:0,height:0};}};
  const controller=Controller.create({api,window:win,document:doc,navigator:{},collection:grid,recordModel:recordModel(),recordsPerPage:52,getRecords:()=>records,setRecords:next=>{records=next;},getState:()=>state,setSuppressAlbumClick(){},setDeleteMode(){},renderGrid:()=>{renders++;},loadCollection:async()=>{reloads++;},onAlert:message=>alerts.push(message),requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:fn=>{fn();return 1;},clearTimeout(){}});
  return {controller,grid,state,rpcCalls,alerts,windowListeners,get records(){return records;},get renders(){return renders;},get reloads(){return reloads;}};
}
test('sorting stays disabled with search/filter/alternate sort or another user',()=>{const h=harness({state:{searchQuery:'pink'}});h.controller.enable();assert.equal(h.grid.classList.contains('grid-sort-enabled'),false);h.state.searchQuery='';h.state.viewedUserId='other';h.controller.enable();assert.equal(h.grid.classList.contains('grid-sort-enabled'),false);});
test('all-record reorder updates local order and collection RPC payload',async()=>{const records=[[1,'A','One',2020,'Rock',0,'',{},1,'id-1',null,{},null,'',null],[2,'B','Two',2021,'Rock',0,'',{},2,'id-2',null,{},null,'',null],[3,'C','Three',2022,'Rock',0,'',{},3,'id-3',null,{},null,'',null]];const h=harness({records,collection:collection([1,0,2])});h.controller.commitDomOrder();await Promise.resolve();await Promise.resolve();assert.deepEqual(h.records.map(r=>r[9]),['id-2','id-1','id-3']);assert.deepEqual(h.records.map(r=>r[0]),[1,2,3]);assert.equal(h.renders,1);assert.deepEqual(h.rpcCalls,[{name:'set_collection_display_order',payload:{p_shelf_id:null,p_collection_ids:['id-2','id-1','id-3']}}]);});
test('active shelf reorder updates shelf order and shelf-scoped RPC payload',async()=>{const records=[[1,'A','One',2020,'Rock',0,'',{},1,'id-1',null,{},null,'s1',1],[2,'B','Two',2021,'Rock',0,'',{},2,'id-2',null,{},null,'s1',2],[3,'C','Three',2022,'Rock',0,'',{},3,'id-3',null,{},null,'s2',1]];const h=harness({records,collection:collection([1,0]),state:{activeShelfId:'s1'}});h.controller.commitDomOrder();await Promise.resolve();await Promise.resolve();assert.equal(records[1][14],1);assert.equal(records[0][14],2);assert.equal(records[2][14],1);assert.deepEqual(h.rpcCalls,[{name:'set_collection_display_order',payload:{p_shelf_id:'s1',p_collection_ids:['id-2','id-1']}}]);});
test('wishlist reorder uses wishlist display-order RPC',async()=>{const records=[[1,'A','One',2020,'Rock',0,'',{},1,'wish-1'],[2,'B','Two',2021,'Rock',0,'',{},2,'wish-2']];const h=harness({records,collection:collection([1,0]),state:{libraryView:'wishlist'}});h.controller.commitDomOrder();await Promise.resolve();await Promise.resolve();assert.deepEqual(h.rpcCalls,[{name:'set_wishlist_display_order',payload:{p_wishlist_ids:['wish-2','wish-1']}}]);});
test('save failure reloads collection and alerts once',async()=>{const h=harness({rpcError:true});await h.controller.queueSave({kind:'collection',shelfId:null,ids:['id-1']});assert.equal(h.alerts.length,1);assert.match(h.alerts[0],/Kunde inte spara den nya ordningen/);assert.equal(h.reloads,1);});

test('re-enabling grid sorting replaces the global blur listener instead of accumulating it',()=>{const h=harness();h.controller.enable();assert.equal(h.windowListeners.get('blur').size,1);h.controller.enable();assert.equal(h.windowListeners.get('blur').size,1);h.state.searchQuery='filter';h.controller.enable();assert.equal(h.windowListeners.get('blur').size,0);});
