create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  added_at timestamp with time zone not null default now(),
  sort_order integer,
  constraint wishlists_user_album_unique unique (user_id, album_id)
);

create index if not exists wishlists_user_id_idx
  on public.wishlists (user_id);

create index if not exists wishlists_album_id_idx
  on public.wishlists (album_id);

alter table public.wishlists enable row level security;

drop policy if exists "Authenticated users can view wishlists" on public.wishlists;
create policy "Authenticated users can view wishlists"
  on public.wishlists
  for select
  to authenticated
  using (true);

drop policy if exists "Users can add to their own wishlist" on public.wishlists;
create policy "Users can add to their own wishlist"
  on public.wishlists
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can remove from their own wishlist" on public.wishlists;
create policy "Users can remove from their own wishlist"
  on public.wishlists
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can reorder their own wishlist" on public.wishlists;
create policy "Users can reorder their own wishlist"
  on public.wishlists
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

revoke all on table public.wishlists from anon;
grant select, insert, update, delete on table public.wishlists to authenticated;
