create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated, service_role;

create table public.community_activity (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  activity_type text not null check (activity_type in ('collection_add','wishlist_add','album_rating')),
  rating integer null check (rating is null or (rating >= 1 and rating <= 5)),
  created_at timestamptz not null default now()
);

alter table public.community_activity enable row level security;

create policy "Authenticated users can read community activity"
  on public.community_activity for select to authenticated using (true);

revoke all on table public.community_activity from anon, authenticated;
grant select on table public.community_activity to authenticated;
grant select, insert, update, delete on table public.community_activity to service_role;
revoke all on sequence public.community_activity_id_seq from anon, authenticated;
grant usage, select on sequence public.community_activity_id_seq to service_role;

create index community_activity_created_at_idx on public.community_activity(created_at desc,id desc);
create index community_activity_actor_id_idx on public.community_activity(actor_id,created_at desc);

insert into public.community_activity(actor_id,album_id,activity_type,rating,created_at)
select c.user_id,c.album_id,'collection_add'::text,null::integer,c.added_at
from public.collections c join public.profiles p on p.id=c.user_id
union all
select w.user_id,w.album_id,'wishlist_add'::text,null::integer,w.added_at
from public.wishlists w join public.profiles p on p.id=w.user_id
union all
select r.user_id,r.album_id,'album_rating'::text,r.rating,r.created_at
from public.album_ratings r join public.profiles p on p.id=r.user_id
where r.rating between 1 and 5;

create or replace function public.log_community_activity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_type text;
  v_actor uuid;
  v_album bigint;
  v_rating integer;
  v_created_at timestamptz;
begin
  if tg_table_name='collections' then
    v_type:='collection_add'; v_actor:=new.user_id; v_album:=new.album_id; v_created_at:=coalesce(new.added_at,now());
  elsif tg_table_name='wishlists' then
    v_type:='wishlist_add'; v_actor:=new.user_id; v_album:=new.album_id; v_created_at:=coalesce(new.added_at,now());
  elsif tg_table_name='album_ratings' then
    if tg_op='UPDATE' and new.rating is not distinct from old.rating then return new; end if;
    if new.rating is null or new.rating < 1 or new.rating > 5 then return new; end if;
    v_type:='album_rating'; v_actor:=new.user_id; v_album:=new.album_id; v_rating:=new.rating;
    v_created_at:=case when tg_op='INSERT' then coalesce(new.created_at,now()) else now() end;
  else
    return new;
  end if;

  if v_actor is null or v_album is null then return new; end if;

  insert into public.community_activity(actor_id,album_id,activity_type,rating,created_at)
  values(v_actor,v_album,v_type,v_rating,v_created_at);
  return new;
end;
$function$;

revoke execute on function public.log_community_activity() from public, anon, authenticated;
grant execute on function public.log_community_activity() to service_role;

create trigger collections_community_activity_after_insert after insert on public.collections
for each row execute function public.log_community_activity();
create trigger wishlists_community_activity_after_insert after insert on public.wishlists
for each row execute function public.log_community_activity();
create trigger album_ratings_community_activity_after_insert after insert on public.album_ratings
for each row execute function public.log_community_activity();
create trigger album_ratings_community_activity_after_update after update of rating on public.album_ratings
for each row execute function public.log_community_activity();

create or replace function private.community_connection_count()
returns bigint
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  select count(*)::bigint from public.user_follows;
$function$;

revoke execute on function private.community_connection_count() from public, anon;
grant execute on function private.community_connection_count() to authenticated, service_role;

create or replace function public.get_community_overview(
  p_limit integer default 5,
  p_activity_limit integer default 8
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public, private, pg_temp
as $function$
declare
  v_user_id uuid := auth.uid();
  v_limit integer := greatest(1,least(coalesce(p_limit,5),10));
  v_activity_limit integer := greatest(1,least(coalesce(p_activity_limit,8),20));
  v_summary jsonb;
  v_similar jsonb;
  v_activity jsonb;
  v_top_collectors jsonb;
  v_top_rated jsonb;
  v_most_collected jsonb;
  v_most_collected_artists jsonb;
  v_most_wishlisted jsonb;
begin
  if v_user_id is null then raise exception 'Not authenticated'; end if;

  select jsonb_build_object(
    'collectors',(select count(*)::bigint from public.profiles),
    'records',(select count(*)::bigint from public.collections),
    'connections',private.community_connection_count()
  ) into v_summary;

  with mine as (
    select c.album_id from public.collections c where c.user_id=v_user_id
  ), mine_count as (
    select count(*)::bigint as count from mine
  ), candidates as (
    select p.id as user_id,p.username,p.avatar_url,
      count(distinct c.album_id)::bigint as collection_count,
      count(distinct c.album_id) filter (where m.album_id is not null)::bigint as common_count,
      mc.count as mine_count
    from public.profiles p
    join public.collections c on c.user_id=p.id
    left join mine m on m.album_id=c.album_id
    cross join mine_count mc
    where p.id<>v_user_id
    group by p.id,p.username,p.avatar_url,mc.count
  ), ranked as (
    select c.*,
      round(case when (c.mine_count+c.collection_count-c.common_count)>0
        then (c.common_count::numeric/(c.mine_count+c.collection_count-c.common_count)::numeric)*100 else 0 end)::integer as similarity_percent,
      exists(select 1 from public.user_follows uf where uf.follower_id=v_user_id and uf.followed_id=c.user_id) as is_following
    from candidates c
    where c.common_count>0
    order by c.common_count desc,similarity_percent desc,c.collection_count desc,c.username
    limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'user_id',r.user_id,'username',r.username,'avatar_url',r.avatar_url,'collection_count',r.collection_count,
    'common_count',r.common_count,'similarity_percent',r.similarity_percent,'is_following',r.is_following
  ) order by r.common_count desc,r.similarity_percent desc,r.collection_count desc,r.username),'[]'::jsonb)
  into v_similar from ranked r;

  with recent as (
    select ca.id,ca.activity_type,ca.rating,ca.created_at,p.id as user_id,p.username,p.avatar_url,
      a.id as album_id,a.title as album_title,a.cover_url,a.discogs_master_id,ar.name as artist_name
    from public.community_activity ca
    join public.profiles p on p.id=ca.actor_id
    join public.albums a on a.id=ca.album_id
    left join public.artists ar on ar.id=a.artist_id
    order by ca.created_at desc,ca.id desc
    limit v_activity_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',r.id,'activity_type',r.activity_type,'rating',r.rating,'created_at',r.created_at,
    'user_id',r.user_id,'username',r.username,'avatar_url',r.avatar_url,
    'album_id',r.album_id,'album_title',r.album_title,'cover_url',r.cover_url,
    'discogs_master_id',r.discogs_master_id,'artist_name',r.artist_name
  ) order by r.created_at desc,r.id desc),'[]'::jsonb)
  into v_activity from recent r;

  with ranked as (
    select p.id as user_id,p.username,p.avatar_url,count(c.id)::bigint as record_count
    from public.profiles p join public.collections c on c.user_id=p.id
    group by p.id,p.username,p.avatar_url
    order by record_count desc,p.username
    limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'user_id',r.user_id,'username',r.username,'avatar_url',r.avatar_url,'record_count',r.record_count
  ) order by r.record_count desc,r.username),'[]'::jsonb)
  into v_top_collectors from ranked r;

  with ranked as (
    select a.id as album_id,a.title,a.cover_url,a.discogs_master_id,ar.name as artist_name,
      round(avg(r.rating)::numeric,1) as average_rating,count(r.id)::bigint as rating_count
    from public.album_ratings r join public.albums a on a.id=r.album_id
    left join public.artists ar on ar.id=a.artist_id
    where r.rating between 1 and 5
    group by a.id,a.title,a.cover_url,a.discogs_master_id,ar.name
    order by average_rating desc,rating_count desc,a.title
    limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'album_id',r.album_id,'title',r.title,'cover_url',r.cover_url,'discogs_master_id',r.discogs_master_id,
    'artist_name',r.artist_name,'average_rating',r.average_rating,'rating_count',r.rating_count
  ) order by r.average_rating desc,r.rating_count desc,r.title),'[]'::jsonb)
  into v_top_rated from ranked r;

  with ranked as (
    select a.id as album_id,a.title,a.cover_url,a.discogs_master_id,ar.name as artist_name,count(c.id)::bigint as collection_count
    from public.collections c join public.albums a on a.id=c.album_id
    left join public.artists ar on ar.id=a.artist_id
    group by a.id,a.title,a.cover_url,a.discogs_master_id,ar.name
    order by collection_count desc,a.title
    limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'album_id',r.album_id,'title',r.title,'cover_url',r.cover_url,'discogs_master_id',r.discogs_master_id,
    'artist_name',r.artist_name,'collection_count',r.collection_count
  ) order by r.collection_count desc,r.title),'[]'::jsonb)
  into v_most_collected from ranked r;

  with ranked as (
    select ar.id as artist_id,ar.name as artist_name,count(c.id)::bigint as collection_count
    from public.collections c join public.albums a on a.id=c.album_id join public.artists ar on ar.id=a.artist_id
    group by ar.id,ar.name
    order by collection_count desc,ar.name
    limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'artist_id',r.artist_id,'artist_name',r.artist_name,'collection_count',r.collection_count
  ) order by r.collection_count desc,r.artist_name),'[]'::jsonb)
  into v_most_collected_artists from ranked r;

  with ranked as (
    select a.id as album_id,a.title,a.cover_url,a.discogs_master_id,ar.name as artist_name,count(w.id)::bigint as wishlist_count
    from public.wishlists w join public.albums a on a.id=w.album_id
    left join public.artists ar on ar.id=a.artist_id
    group by a.id,a.title,a.cover_url,a.discogs_master_id,ar.name
    order by wishlist_count desc,a.title
    limit v_limit
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'album_id',r.album_id,'title',r.title,'cover_url',r.cover_url,'discogs_master_id',r.discogs_master_id,
    'artist_name',r.artist_name,'wishlist_count',r.wishlist_count
  ) order by r.wishlist_count desc,r.title),'[]'::jsonb)
  into v_most_wishlisted from ranked r;

  return jsonb_build_object(
    'summary',coalesce(v_summary,'{}'::jsonb),
    'similar_collectors',coalesce(v_similar,'[]'::jsonb),
    'activity',coalesce(v_activity,'[]'::jsonb),
    'top_collectors',coalesce(v_top_collectors,'[]'::jsonb),
    'top_rated_albums',coalesce(v_top_rated,'[]'::jsonb),
    'most_collected_albums',coalesce(v_most_collected,'[]'::jsonb),
    'most_collected_artists',coalesce(v_most_collected_artists,'[]'::jsonb),
    'most_wishlisted_albums',coalesce(v_most_wishlisted,'[]'::jsonb)
  );
end;
$function$;

revoke execute on function public.get_community_overview(integer,integer) from public, anon;
grant execute on function public.get_community_overview(integer,integer) to authenticated, service_role;
