-- Global Web Push infrastructure for Groovy.
-- Price Alerts use push by default when a mobile device has granted permission.
-- notification_preferences is intentionally generic so a future Settings page can
-- turn individual notification categories on/off without changing alert rows.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  platform text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0 check (failure_count >= 0)
);

create index if not exists push_subscriptions_user_id_idx
  on public.push_subscriptions(user_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists push_subscriptions_select_own
  on public.push_subscriptions;

create policy push_subscriptions_select_own
on public.push_subscriptions
for select
to authenticated
using (user_id = (select auth.uid()));

revoke all on table public.push_subscriptions from anon, authenticated;
grant select on table public.push_subscriptions to authenticated;
grant all on table public.push_subscriptions to service_role;

create table if not exists public.notification_preferences (
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null
    check (
      char_length(notification_type) between 1 and 64
      and notification_type ~ '^[a-z0-9_]+$'
    ),
  push_enabled boolean not null default true,
  in_app_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (user_id, notification_type)
);

alter table public.notification_preferences enable row level security;

drop policy if exists notification_preferences_select_own
  on public.notification_preferences;
drop policy if exists notification_preferences_insert_own
  on public.notification_preferences;
drop policy if exists notification_preferences_update_own
  on public.notification_preferences;
drop policy if exists notification_preferences_delete_own
  on public.notification_preferences;

create policy notification_preferences_select_own
on public.notification_preferences
for select to authenticated
using (user_id = (select auth.uid()));

create policy notification_preferences_insert_own
on public.notification_preferences
for insert to authenticated
with check (user_id = (select auth.uid()));

create policy notification_preferences_update_own
on public.notification_preferences
for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy notification_preferences_delete_own
on public.notification_preferences
for delete to authenticated
using (user_id = (select auth.uid()));

revoke all on table public.notification_preferences from anon, authenticated;
grant select,insert,update,delete on table public.notification_preferences to authenticated;
grant all on table public.notification_preferences to service_role;

create or replace function public.save_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default '',
  p_platform text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  uid uuid := auth.uid();
  saved public.push_subscriptions;
  endpoint_value text := trim(coalesce(p_endpoint,''));
  p256dh_value text := trim(coalesce(p_p256dh,''));
  auth_value text := trim(coalesce(p_auth,''));
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if endpoint_value !~ '^https://' or char_length(endpoint_value) > 4000 then
    raise exception 'Invalid push endpoint';
  end if;
  if char_length(p256dh_value) < 20 or char_length(p256dh_value) > 500 then
    raise exception 'Invalid push key';
  end if;
  if char_length(auth_value) < 8 or char_length(auth_value) > 500 then
    raise exception 'Invalid push auth secret';
  end if;

  insert into public.push_subscriptions(
    user_id,endpoint,p256dh,auth,user_agent,platform,updated_at,failure_count
  ) values (
    uid,endpoint_value,p256dh_value,auth_value,
    left(coalesce(p_user_agent,''),1000),
    left(coalesce(p_platform,''),120),
    now(),0
  )
  on conflict(endpoint) do update set
    user_id=excluded.user_id,
    p256dh=excluded.p256dh,
    auth=excluded.auth,
    user_agent=excluded.user_agent,
    platform=excluded.platform,
    updated_at=now(),
    failure_count=0
  returning * into saved;

  return to_jsonb(saved);
end;
$function$;

revoke execute on function public.save_push_subscription(text,text,text,text,text)
  from public, anon;
grant execute on function public.save_push_subscription(text,text,text,text,text)
  to authenticated, service_role;

create or replace function public.delete_push_subscription(p_endpoint text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  uid uuid := auth.uid();
  deleted_count integer := 0;
begin
  if uid is null then raise exception 'Authentication required'; end if;

  delete from public.push_subscriptions
  where user_id=uid and endpoint=trim(coalesce(p_endpoint,''));

  get diagnostics deleted_count = row_count;
  return deleted_count > 0;
end;
$function$;

revoke execute on function public.delete_push_subscription(text)
  from public, anon;
grant execute on function public.delete_push_subscription(text)
  to authenticated, service_role;

-- Edge Functions use this service-role-only RPC so the VAPID private key never
-- lives in the repository or browser.
create or replace function public.get_web_push_vapid_config()
returns jsonb
language sql
security definer
set search_path = public, vault, pg_temp
as $function$
  select jsonb_build_object(
    'public_key', coalesce(max(decrypted_secret) filter (where name='web_push_vapid_public_key'),''),
    'private_key', coalesce(max(decrypted_secret) filter (where name='web_push_vapid_private_key'),''),
    'subject', coalesce(max(decrypted_secret) filter (where name='web_push_vapid_subject'),'')
  )
  from vault.decrypted_secrets
  where name in (
    'web_push_vapid_public_key',
    'web_push_vapid_private_key',
    'web_push_vapid_subject'
  );
$function$;

revoke execute on function public.get_web_push_vapid_config()
  from public, anon, authenticated;
grant execute on function public.get_web_push_vapid_config()
  to service_role;
