-- Marketplace price alerts: user-owned thresholds plus service-role scanning.
-- Background scans are invoked hourly by pg_cron and deduplicate listings per alert.

create extension if not exists pg_net;
create extension if not exists pg_cron with schema pg_catalog;

create table if not exists public.marketplace_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  album_id bigint not null references public.albums(id) on delete cascade,
  max_price numeric(12,2) not null check (max_price > 0),
  currency text not null check (currency in ('SEK','EUR','USD','GBP','NOK','DKK','CHF','CAD','AUD','JPY','PLN','CZK')),
  tradera_enabled boolean not null default true,
  ebay_enabled boolean not null default true,
  fixed_price boolean not null default true,
  auction boolean not null default true,
  ebay_marketplace_id text not null default 'EBAY_US',
  active boolean not null default true,
  last_checked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketplace_alerts_marketplace_check check (tradera_enabled or ebay_enabled),
  constraint marketplace_alerts_sale_type_check check (fixed_price or auction),
  constraint marketplace_alerts_user_album_unique unique (user_id,album_id)
);

create index if not exists marketplace_alerts_scan_idx
  on public.marketplace_alerts (active,last_checked_at);

alter table public.marketplace_alerts enable row level security;

drop policy if exists marketplace_alerts_select_own on public.marketplace_alerts;
create policy marketplace_alerts_select_own
on public.marketplace_alerts
for select
to authenticated
using (user_id = auth.uid());

revoke all on table public.marketplace_alerts from anon, authenticated;
grant select on table public.marketplace_alerts to authenticated;
grant all on table public.marketplace_alerts to service_role;

create table if not exists public.marketplace_alert_matches (
  id bigint generated by default as identity primary key,
  alert_id bigint not null references public.marketplace_alerts(id) on delete cascade,
  marketplace text not null check (marketplace in ('Tradera','eBay')),
  listing_id text not null,
  sale_type text not null check (sale_type in ('fixed','auction')),
  listing_title text not null default '',
  listing_url text not null,
  original_price numeric(12,2) not null check (original_price > 0),
  original_currency text not null,
  matched_price numeric(12,2) not null check (matched_price > 0),
  alert_currency text not null,
  first_seen_at timestamptz not null default now(),
  notified_at timestamptz not null default now(),
  constraint marketplace_alert_matches_unique unique (alert_id,marketplace,listing_id)
);

create index if not exists marketplace_alert_matches_alert_idx
  on public.marketplace_alert_matches (alert_id,first_seen_at desc);

alter table public.marketplace_alert_matches enable row level security;
revoke all on table public.marketplace_alert_matches from anon, authenticated;
grant all on table public.marketplace_alert_matches to service_role;

alter table public.notifications
  alter column actor_id drop not null;

alter table public.notifications
  drop constraint if exists notifications_type_check;

alter table public.notifications
  add constraint notifications_type_check
  check (notification_type in (
    'new_follower',
    'collection_activity',
    'wishlist_match',
    'album_review',
    'review_like',
    'price_alert'
  ));

create or replace function public.save_marketplace_alert(
  p_album_id bigint,
  p_max_price numeric,
  p_currency text,
  p_tradera boolean,
  p_ebay boolean,
  p_fixed boolean,
  p_auction boolean,
  p_ebay_marketplace_id text default 'EBAY_US'
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  uid uuid := auth.uid();
  saved public.marketplace_alerts;
  normalized_currency text := upper(trim(coalesce(p_currency,'')));
  normalized_marketplace text := upper(trim(coalesce(p_ebay_marketplace_id,'EBAY_US')));
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if p_album_id is null or not exists(select 1 from public.albums where id=p_album_id) then
    raise exception 'Album not found';
  end if;
  if p_max_price is null or p_max_price <= 0 or p_max_price > 10000000 then
    raise exception 'Invalid alert price';
  end if;
  if normalized_currency not in ('SEK','EUR','USD','GBP','NOK','DKK','CHF','CAD','AUD','JPY','PLN','CZK') then
    raise exception 'Unsupported currency';
  end if;
  if not coalesce(p_tradera,false) and not coalesce(p_ebay,false) then
    raise exception 'Choose at least one marketplace';
  end if;
  if not coalesce(p_fixed,false) and not coalesce(p_auction,false) then
    raise exception 'Choose at least one sale type';
  end if;
  if normalized_marketplace not in (
    'EBAY_US','EBAY_AT','EBAY_AU','EBAY_BE','EBAY_CA','EBAY_CH','EBAY_DE',
    'EBAY_ES','EBAY_FR','EBAY_GB','EBAY_HK','EBAY_IE','EBAY_IT','EBAY_MY',
    'EBAY_NL','EBAY_PH','EBAY_PL','EBAY_SG','EBAY_TW'
  ) then
    normalized_marketplace := 'EBAY_US';
  end if;

  insert into public.marketplace_alerts (
    user_id,album_id,max_price,currency,tradera_enabled,ebay_enabled,
    fixed_price,auction,ebay_marketplace_id,active,updated_at
  ) values (
    uid,p_album_id,round(p_max_price,2),normalized_currency,coalesce(p_tradera,false),coalesce(p_ebay,false),
    coalesce(p_fixed,false),coalesce(p_auction,false),normalized_marketplace,true,now()
  )
  on conflict (user_id,album_id) do update set
    max_price=excluded.max_price,
    currency=excluded.currency,
    tradera_enabled=excluded.tradera_enabled,
    ebay_enabled=excluded.ebay_enabled,
    fixed_price=excluded.fixed_price,
    auction=excluded.auction,
    ebay_marketplace_id=excluded.ebay_marketplace_id,
    active=true,
    last_error=null,
    updated_at=now()
  returning * into saved;

  return to_jsonb(saved);
end;
$function$;

revoke execute on function public.save_marketplace_alert(bigint,numeric,text,boolean,boolean,boolean,boolean,text)
  from public, anon;
grant execute on function public.save_marketplace_alert(bigint,numeric,text,boolean,boolean,boolean,boolean,text)
  to authenticated, service_role;

create or replace function public.delete_marketplace_alert(p_album_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  uid uuid := auth.uid();
  deleted_count integer := 0;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  delete from public.marketplace_alerts where user_id=uid and album_id=p_album_id;
  get diagnostics deleted_count = row_count;
  return deleted_count > 0;
end;
$function$;

revoke execute on function public.delete_marketplace_alert(bigint) from public, anon;
grant execute on function public.delete_marketplace_alert(bigint) to authenticated, service_role;

create table if not exists public.marketplace_alert_scan_state (
  singleton boolean primary key default true check (singleton),
  last_started_at timestamptz,
  last_finished_at timestamptz,
  last_status text,
  last_error text
);

alter table public.marketplace_alert_scan_state enable row level security;
revoke all on table public.marketplace_alert_scan_state from anon, authenticated;
grant all on table public.marketplace_alert_scan_state to service_role;

insert into public.marketplace_alert_scan_state(singleton,last_status)
values (true,'idle')
on conflict (singleton) do nothing;

create or replace function public.claim_marketplace_alert_scan(p_min_interval_minutes integer default 55)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  claimed boolean := false;
begin
  update public.marketplace_alert_scan_state
  set last_started_at=now(),last_status='running',last_error=null
  where singleton=true
    and (
      last_started_at is null or
      last_started_at < now() - make_interval(mins => greatest(1,coalesce(p_min_interval_minutes,55)))
    )
  returning true into claimed;
  return coalesce(claimed,false);
end;
$function$;

revoke execute on function public.claim_marketplace_alert_scan(integer)
  from public, anon, authenticated;
grant execute on function public.claim_marketplace_alert_scan(integer)
  to service_role;

create or replace function public.finish_marketplace_alert_scan(p_error text default null)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  update public.marketplace_alert_scan_state
  set
    last_finished_at=now(),
    last_status=case when nullif(trim(coalesce(p_error,'')),'') is null then 'ok' else 'error' end,
    last_error=nullif(left(trim(coalesce(p_error,'')),1000),'')
  where singleton=true;
end;
$function$;

revoke execute on function public.finish_marketplace_alert_scan(text)
  from public, anon, authenticated;
grant execute on function public.finish_marketplace_alert_scan(text)
  to service_role;

create or replace function public.record_marketplace_alert_scan(
  p_alert_id bigint,
  p_matches jsonb default '[]'::jsonb,
  p_error text default null
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  alert_row public.marketplace_alerts;
  item jsonb;
  inserted_rows integer;
  inserted_count integer := 0;
  latest_match jsonb := null;
  existing_notification_id bigint;
  album_title text := '';
  album_artist text := '';
  album_cover text := '';
begin
  select * into alert_row
  from public.marketplace_alerts
  where id=p_alert_id and active=true
  for update;

  if not found then return 0; end if;

  if jsonb_typeof(coalesce(p_matches,'[]'::jsonb))='array' then
    for item in select value from jsonb_array_elements(coalesce(p_matches,'[]'::jsonb))
    loop
      if coalesce(item->>'marketplace','') not in ('Tradera','eBay') then continue; end if;
      if coalesce(item->>'sale_type','') not in ('fixed','auction') then continue; end if;
      if trim(coalesce(item->>'listing_id',''))='' or trim(coalesce(item->>'listing_url',''))='' then continue; end if;

      insert into public.marketplace_alert_matches(
        alert_id,marketplace,listing_id,sale_type,listing_title,listing_url,
        original_price,original_currency,matched_price,alert_currency
      ) values (
        alert_row.id,
        item->>'marketplace',
        left(item->>'listing_id',300),
        item->>'sale_type',
        left(coalesce(item->>'listing_title',''),500),
        left(item->>'listing_url',2000),
        greatest(0.01,(item->>'original_price')::numeric),
        upper(left(coalesce(item->>'original_currency',alert_row.currency),8)),
        greatest(0.01,(item->>'matched_price')::numeric),
        alert_row.currency
      )
      on conflict (alert_id,marketplace,listing_id) do nothing;

      get diagnostics inserted_rows = row_count;
      if inserted_rows > 0 then
        inserted_count := inserted_count + 1;
        if latest_match is null or (item->>'matched_price')::numeric < (latest_match->>'matched_price')::numeric then
          latest_match := item;
        end if;
      end if;
    end loop;
  end if;

  update public.marketplace_alerts
  set last_checked_at=now(),last_error=nullif(left(trim(coalesce(p_error,'')),1000),'')
  where id=alert_row.id;

  if inserted_count=0 then return 0; end if;

  select coalesce(a.title,''),coalesce(ar.name,''),coalesce(a.cover_url,'')
  into album_title,album_artist,album_cover
  from public.albums a
  left join public.artists ar on ar.id=a.artist_id
  where a.id=alert_row.album_id;

  update public.notifications n
  set
    item_count=n.item_count+inserted_count,
    payload=jsonb_build_object(
      'alert_id',alert_row.id,
      'album_id',alert_row.album_id,
      'album_title',album_title,
      'album_artist',album_artist,
      'cover_url',album_cover,
      'threshold',alert_row.max_price,
      'alert_currency',alert_row.currency,
      'marketplace',latest_match->>'marketplace',
      'listing_id',latest_match->>'listing_id',
      'listing_title',latest_match->>'listing_title',
      'listing_url',latest_match->>'listing_url',
      'sale_type',latest_match->>'sale_type',
      'original_price',latest_match->>'original_price',
      'original_currency',latest_match->>'original_currency',
      'matched_price',latest_match->>'matched_price'
    ),
    updated_at=now()
  where n.recipient_id=alert_row.user_id
    and n.notification_type='price_alert'
    and n.actor_id is null
    and n.read_at is null
    and n.payload->>'alert_id'=alert_row.id::text
  returning n.id into existing_notification_id;

  if existing_notification_id is null then
    insert into public.notifications(
      recipient_id,actor_id,notification_type,item_count,payload,created_at,updated_at
    ) values (
      alert_row.user_id,null,'price_alert',inserted_count,
      jsonb_build_object(
        'alert_id',alert_row.id,
        'album_id',alert_row.album_id,
        'album_title',album_title,
        'album_artist',album_artist,
        'cover_url',album_cover,
        'threshold',alert_row.max_price,
        'alert_currency',alert_row.currency,
        'marketplace',latest_match->>'marketplace',
        'listing_id',latest_match->>'listing_id',
        'listing_title',latest_match->>'listing_title',
        'listing_url',latest_match->>'listing_url',
        'sale_type',latest_match->>'sale_type',
        'original_price',latest_match->>'original_price',
        'original_currency',latest_match->>'original_currency',
        'matched_price',latest_match->>'matched_price'
      ),
      now(),now()
    );
  end if;

  return inserted_count;
end;
$function$;

revoke execute on function public.record_marketplace_alert_scan(bigint,jsonb,text)
  from public, anon, authenticated;
grant execute on function public.record_marketplace_alert_scan(bigint,jsonb,text)
  to service_role;

do $cron$
begin
  perform cron.schedule(
    'marketplace-alert-scan-hourly',
    '13 * * * *',
    $job$
      select net.http_post(
        url := (select decrypted_secret from vault.decrypted_secrets where name='marketplace_alert_project_url')
          || '/functions/v1/marketplace-alert-scan',
        headers := jsonb_build_object(
          'Content-Type','application/json',
          'Authorization','Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name='marketplace_alert_anon_jwt'),
          'apikey',(select decrypted_secret from vault.decrypted_secrets where name='marketplace_alert_publishable_key')
        ),
        body := jsonb_build_object('source','cron','scheduled_at',now()),
        timeout_milliseconds := 20000
      );
    $job$
  );
end;
$cron$;
