-- Replace browser Web Push storage with native app device registrations.
-- Android uses FCM. The same table is ready for a future iOS/APNs app.
-- Notification preferences remain generic and are intentionally preserved.

drop function if exists public.save_push_subscription(text,text,text,text,text);
drop function if exists public.delete_push_subscription(text);
drop function if exists public.get_web_push_vapid_config();
drop function if exists public.initialize_web_push_vapid(text,text,text);

drop table if exists public.push_subscriptions cascade;

delete from vault.secrets
where name in (
  'web_push_vapid_public_key',
  'web_push_vapid_private_key',
  'web_push_vapid_subject'
);

create table if not exists public.native_push_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('android','ios')),
  provider text not null check (provider in ('fcm','apns')),
  device_token text not null unique,
  app_id text not null default '',
  app_version text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0 check (failure_count >= 0)
);

create index if not exists native_push_devices_user_id_idx
  on public.native_push_devices(user_id);

alter table public.native_push_devices enable row level security;

drop policy if exists native_push_devices_select_own
  on public.native_push_devices;

create policy native_push_devices_select_own
on public.native_push_devices
for select
to authenticated
using (user_id = (select auth.uid()));

revoke all on table public.native_push_devices from anon, authenticated;
grant select on table public.native_push_devices to authenticated;
grant all on table public.native_push_devices to service_role;

create or replace function public.register_native_push_device(
  p_platform text,
  p_provider text,
  p_device_token text,
  p_app_id text default '',
  p_app_version text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  uid uuid := auth.uid();
  platform_value text := lower(trim(coalesce(p_platform,'')));
  provider_value text := lower(trim(coalesce(p_provider,'')));
  token_value text := trim(coalesce(p_device_token,''));
  saved public.native_push_devices;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if platform_value not in ('android','ios') then raise exception 'Invalid platform'; end if;
  if provider_value not in ('fcm','apns') then raise exception 'Invalid provider'; end if;
  if platform_value='android' and provider_value<>'fcm' then raise exception 'Android requires FCM'; end if;
  if platform_value='ios' and provider_value<>'apns' then raise exception 'iOS requires APNs'; end if;
  if char_length(token_value)<20 or char_length(token_value)>4096 then raise exception 'Invalid device token'; end if;

  insert into public.native_push_devices(
    user_id,platform,provider,device_token,app_id,app_version,active,updated_at,failure_count
  ) values (
    uid,platform_value,provider_value,token_value,
    left(coalesce(p_app_id,''),200),
    left(coalesce(p_app_version,''),80),
    true,now(),0
  )
  on conflict(device_token) do update set
    user_id=excluded.user_id,
    platform=excluded.platform,
    provider=excluded.provider,
    app_id=excluded.app_id,
    app_version=excluded.app_version,
    active=true,
    updated_at=now(),
    failure_count=0
  returning * into saved;

  return to_jsonb(saved);
end;
$function$;

revoke execute on function public.register_native_push_device(text,text,text,text,text)
  from public, anon;
grant execute on function public.register_native_push_device(text,text,text,text,text)
  to authenticated, service_role;

create or replace function public.delete_native_push_device(p_device_token text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  uid uuid := auth.uid();
  deleted_count integer := 0;
begin
  if uid is null then raise exception 'Authentication required'; end if;

  delete from public.native_push_devices
  where user_id=uid and device_token=trim(coalesce(p_device_token,''));

  get diagnostics deleted_count = row_count;
  return deleted_count>0;
end;
$function$;

revoke execute on function public.delete_native_push_device(text)
  from public, anon;
grant execute on function public.delete_native_push_device(text)
  to authenticated, service_role;
