-- Album reviews live at album level, independent of a user's physical pressing.
create table public.album_reviews (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.albums(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint album_reviews_user_album_key unique (user_id,album_id),
  constraint album_reviews_body_length_check
    check (char_length(btrim(body)) between 1 and 2000)
);

create index album_reviews_album_created_idx
  on public.album_reviews(album_id,created_at desc);
create index album_reviews_user_idx
  on public.album_reviews(user_id);

create table public.album_review_likes (
  review_id bigint not null references public.album_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (review_id,user_id)
);

create index album_review_likes_user_idx
  on public.album_review_likes(user_id);

alter table public.album_reviews enable row level security;
alter table public.album_review_likes enable row level security;

revoke all on table public.album_reviews from public,anon,authenticated;
grant select,insert,update,delete on table public.album_reviews to authenticated;
grant select,insert,update,delete on table public.album_reviews to service_role;

revoke all on table public.album_review_likes from public,anon,authenticated;
grant select,insert,delete on table public.album_review_likes to authenticated;
grant select,insert,update,delete on table public.album_review_likes to service_role;

create policy "Authenticated users can read album reviews"
  on public.album_reviews
  for select to authenticated
  using (true);

create policy "Users can add own album reviews"
  on public.album_reviews
  for insert to authenticated
  with check ((select auth.uid())=user_id);

create policy "Users can update own album reviews"
  on public.album_reviews
  for update to authenticated
  using ((select auth.uid())=user_id)
  with check ((select auth.uid())=user_id);

create policy "Users can delete own album reviews"
  on public.album_reviews
  for delete to authenticated
  using ((select auth.uid())=user_id);

create policy "Authenticated users can read review likes"
  on public.album_review_likes
  for select to authenticated
  using (true);

create policy "Users can like reviews"
  on public.album_review_likes
  for insert to authenticated
  with check (
    (select auth.uid())=user_id
    and exists (
      select 1
      from public.album_reviews r
      where r.id=review_id
        and r.user_id<>(select auth.uid())
    )
  );

create policy "Users can remove own review likes"
  on public.album_review_likes
  for delete to authenticated
  using ((select auth.uid())=user_id);

create or replace function private.touch_album_review_updated_at()
returns trigger
language plpgsql
set search_path=public,pg_temp
as $function$
begin
  new.updated_at=now();
  return new;
end;
$function$;

revoke all on function private.touch_album_review_updated_at()
  from public,anon,authenticated;

create trigger touch_album_review_updated_at
before update on public.album_reviews
for each row execute function private.touch_album_review_updated_at();

create or replace function public.save_album_review(
  p_album_id bigint,
  p_rating integer,
  p_body text
)
returns bigint
language plpgsql
security invoker
set search_path=public,pg_temp
as $function$
declare
  v_user_id uuid := auth.uid();
  v_body text := btrim(coalesce(p_body,''));
  v_review_id bigint;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;
  if p_album_id is null then
    raise exception 'Album is required';
  end if;
  if p_rating is null or p_rating<1 or p_rating>5 then
    raise exception 'Rating must be between 1 and 5';
  end if;
  if char_length(v_body)<1 or char_length(v_body)>2000 then
    raise exception 'Review must be between 1 and 2000 characters';
  end if;

  insert into public.album_ratings(user_id,album_id,rating)
  values (v_user_id,p_album_id,p_rating)
  on conflict (user_id,album_id)
  do update set rating=excluded.rating;

  insert into public.album_reviews(album_id,user_id,body)
  values (p_album_id,v_user_id,v_body)
  on conflict (user_id,album_id)
  do update set body=excluded.body,updated_at=now()
  returning id into v_review_id;

  return v_review_id;
end;
$function$;

revoke execute on function public.save_album_review(bigint,integer,text)
  from public,anon;
grant execute on function public.save_album_review(bigint,integer,text)
  to authenticated,service_role;
